export const GRAVITY = -12
export const JUMP_FORCE = 4
export const MOVE_SPEED = 3.5
export const SPRINT_MULTIPLIER = 2.0
export const CROUCH_MULTIPLIER = 0.4
export const SWIM_SPEED = 2.5
export const GLIDE_GRAVITY = -2
export const STAMINA_DRAIN_RATE = 15 // per second while sprinting
export const STAMINA_RECOVER_RATE = 10 // per second while not sprinting
export const FALL_DAMAGE_THRESHOLD = 12 // velocity threshold
export const FALL_DAMAGE_MULTIPLIER = 3
export const PLAYER_HEIGHT = 0.8 // ant scale
export const PLAYER_CROUCH_HEIGHT = 0.4
export const WATER_LEVEL = -0.5
